//
//  NSObject+ESAutoCoding.h
//  ESFramework
//
//  Created by Elf Sundae on 15/8/22.
//  Copyright (c) 2015年 www.0x123.com. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/* Implementation for -[NSCopying copyWithZone:] */
#define ES_IMPLEMENTATION_NSCopying_copyWithZone                \
    - (id)copyWithZone:(NSZone *)zone {                         \
        id copy = [[[self class] alloc] init];                  \
        for (NSString *key in self.codableProperties) {         \
            [copy setValue:[self valueForKey:key] forKey:key];  \
        }                                                       \
        return copy;                                            \
    }

/*!
 * The ESAutoCoding category on NSObject provides automatic support for
 * NSCoding and NSCopying to any object, it is inspired by
 * [nicklockwood/AutoCoding](https://github.com/nicklockwood/AutoCoding).
 *
 * Tips: https://github.com/nicklockwood/AutoCoding#tips
 *
 * @code
 * @interface User : NSObject <NSCopying>
 * @property (nonatomic, copy) NSString *name;
 * @end
 *
 * @implementation User
 *
 * ES_IMPLEMENTATION_NSCopying_copyWithZone
 *
 * - (NSUInteger)hash
 * {
 *     //
 * }
 *
 * - (BOOL)isEqual:(id)object
 * {
 *     //
 * }
 *
 * @end
 * @endcode
 *
 * @note Your object should conform to NSSecureCoding instead NSCoding whenever possible.
 */
@interface NSObject (ESAutoCoding) <NSSecureCoding>

/**
 * Populates the object's properties using the provided `NSCoder` object, based
 * on the `codableProperties` dictionary. This is called internally by the
 * `initWithCoder:` method, but may be useful if you wish to initialise an object
 * from a coded archive after it has already been created. You could even
 * initialise the object by merging the results of several different archives by
 * calling `setWithCoder:` more than once.
 */
- (void)setWithCoder:(NSCoder *)aDecoder;

/**
 * Returns all the codable properties of the object, including those that are
 * inherited from superclasses.
 *
 * @warning You should not override this method - if you want to add additional
 * properties, override the `+codableProperties` class method instead.
 */
@property (nonatomic, readonly) NSDictionary<NSString *, Class> *codableProperties;

/**
 * Returns a dictionary of the values of all the codable properties.
 */
@property (nonatomic, readonly) NSDictionary<NSString *, id> *dictionaryRepresentation;

/**
 * Returns an NSData object containing the encoded form of the object.
 */
@property (nullable, nonatomic, readonly) NSData *archivedData;

/**
 * Writes the archived data to the file specified by a given path.
 */
- (BOOL)writeToFile:(NSString *)path atomically:(BOOL)atomically;

/**
 * Writes the archived data to the location specified by a given URL.
 */
- (BOOL)writeToURL:(NSURL *)url atomically:(BOOL)atomically;

/**
 * Decodes and returns the object previously encoded and stored in a given
 * NSData object.
 */
+ (nullable instancetype)objectWithArchivedData:(NSData *)data;

/**
 * Creates and returns an object previously encoded and stored to the file
 * specified by a given path.
 */
+ (nullable instancetype)objectWithContentsOfFile:(NSString *)path;

/**
 * Creates and returns an object previously encoded and stored to the location
 * specified by a given URL.
 */
+ (nullable instancetype)objectWithContentsOfURL:(NSURL *)url;

/**
 * Returns a dictionary containing the names and classes of all the properties of
 * the class that will be automatically saved, loaded and copied when the object
 * is archived using `NSKeyedArchiver/Unarchiver`. The values of the dictionary
 * represent the class used to encode each property (e.g. `NSString` for strings,
 * `NSNumber` for numeric values or booleans, `NSValue` for structs, etc).
 *
 * This dictionary is automatically generated by scanning the properties defined
 * in the class definition at runtime. Read-only and private properties will also
 * be coded as long as they have KVC-compliant ivar names (i.e. the ivar matches
 * the property name, or is the same but with a _ prefix). Any properties that
 * are not backed by an ivar, or whose ivar name does not match the property name
 * will not be encoded (this is a design feature, not a limitation - it makes it
 * easier to exclude properties from encoding)
 *
 * It is not normally necessary to override this method unless you wish to add
 * ivars for coding that do not have matching property definitions, or if you
 * wish to code virtual properties (properties or setter/getter method pairs that
 * are not backed by an ivar). If you wish to exclude certain properties from the
 * serialisation process, you can deliberately give them an non KVC-compliant
 * ivar name (see above).
 *
 * Note that this method only returns the properties defined on a particular
 * class and not any properties that are inherited from its superclasses. You
 * *do not* need to call `[super codableProperties]` if you override this method.
 */
+ (NSDictionary<NSString *, Class> *)codableProperties;

@end

NS_ASSUME_NONNULL_END
