name: Example

options:
  bundleIdPrefix: com.0x123.ESFramework
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    iOS: '9.0'
    tvOS: '9.0'
    macOS: '10.11'
    watchOS: '2.0'

attributes:
  ORGANIZATIONNAME: 'https://0x123.com '

targetTemplates:
  Example:
    type: application
    sources: ["${target_name}"]
    settings:
      DEVELOPMENT_TEAM: B86YZY7YJX
      PRODUCT_NAME: ESFramework
      # Fix warning for Xcode 11.3
      CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

targets:
  iOS Example:
    templates: [Example]
    platform: iOS
    sources: [Model]
    settings:
      CODE_SIGN_ENTITLEMENTS: ${target_name}/${target_name}.entitlements
    dependencies:
      - target: watchOS Example
      - framework: ESFramework.framework
        implicit: true

  macOS Example:
    templates: [Example]
    platform: macOS
    settings:
      CODE_SIGN_ENTITLEMENTS: ${target_name}/${target_name}.entitlements
    dependencies:
      - framework: ESFramework.framework
        implicit: true

  tvOS Example:
    templates: [Example]
    platform: tvOS
    dependencies:
      - framework: ESFramework.framework
        implicit: true

  watchOS Example:
    templates: [Example]
    type: application.watchapp2
    platform: watchOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.0x123.ESFramework.iOSExample.watchkitapp
    dependencies:
      - target: watchOS Example Extension

  watchOS Example Extension:
    templates: [Example]
    type: watchkit2-extension
    platform: watchOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.0x123.ESFramework.iOSExample.watchkitapp.watchkitextension
