name: ESFramework

options:
  bundleIdPrefix: com.0x123.ESFramework
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    iOS: '8.0'
    tvOS: '9.0'
    macOS: '10.10'
    watchOS: '2.0'

attributes:
  CLASSPREFIX: ES
  ORGANIZATIONNAME: 'https://0x123.com'

settings:
  MARKETING_VERSION: 3.22.2
  CURRENT_PROJECT_VERSION: 3
  # Fix warning for Xcode 11.3: Enable "Missing Localizability"
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

targetTemplates:
  Framework:
    type: framework
    scheme: {} # To generate default shared schemes: https://github.com/yonaskolb/XcodeGen/issues/215
    sources:
      - ESFramework/ESFramework.h
      - ESFramework/Foundation
      - Supporting Files/Info.plist
    settings:
      PRODUCT_NAME: ESFramework
      PRODUCT_BUNDLE_IDENTIFIER: com.0x123.ESFramework
      APPLICATION_EXTENSION_API_ONLY: YES
  Example:
    type: application
    sources: ["Examples/${target_name}"]
    settings:
      DEVELOPMENT_TEAM: B86YZY7YJX

targets:
  ESFramework-iOS:
    platform: iOS
    templates: [Framework]
    sources: [ESFramework]

  ESFramework-tvOS:
    platform: tvOS
    templates: [Framework]
    sources: [ESFramework]

  ESFramework-macOS:
    platform: macOS
    templates: [Framework]
    sources: [ESFramework/Network]

  ESFramework-watchOS:
    platform: watchOS
    templates: [Framework]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.0x123.ESFramework-watchOS

  iOS Example:
    platform: iOS
    templates: [Example]
    settings:
      CODE_SIGN_ENTITLEMENTS: Examples/${target_name}/${target_name}.entitlements
    dependencies:
      - target: ESFramework-iOS
      - target: watchOS Example

  tvOS Example:
    platform: tvOS
    templates: [Example]
    dependencies:
      - target: ESFramework-tvOS

  macOS Example:
    platform: macOS
    templates: [Example]
    settings:
      CODE_SIGN_ENTITLEMENTS: Examples/${target_name}/${target_name}.entitlements
      CODE_SIGN_IDENTITY: '-'
    dependencies:
      - target: ESFramework-macOS

  watchOS Example:
    platform: watchOS
    type: application.watchapp2
    templates: [Example]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.0x123.ESFramework.iOSExample.watchkitapp
    dependencies:
      - target: watchOS Example Extension

  watchOS Example Extension:
    platform: watchOS
    type: watchkit2-extension
    templates: [Example]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.0x123.ESFramework.iOSExample.watchkitapp.watchkitextension
    dependencies:
      - target: ESFramework-watchOS
