name: ESFramework

options:
  bundleIdPrefix: com.0x123
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    iOS: '9.0'
    tvOS: '9.0'
    macOS: '10.11'
    watchOS: '2.0'

attributes:
  CLASSPREFIX: ES
  ORGANIZATIONNAME: 'https://0x123.com '

targets:
  ESFramework:
    type: framework
    platform: [iOS, tvOS, macOS, watchOS]
    sources:
      - ESFramework
      - Supporting Files/Info.plist
