name: ESFramework

options:
  bundleIdPrefix: com.0x123
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    iOS: '9.0'
    tvOS: '9.0'
    macOS: '10.10'
    watchOS: '2.0'

attributes:
  CLASSPREFIX: ES
  ORGANIZATIONNAME: 'https://0x123.com'

settings:
  MARKETING_VERSION: 3.27.3
  CURRENT_PROJECT_VERSION: 3
  # Fix warning for Xcode 11.3: Enable "Missing Localizability"
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
  # Xcode 12 default setting
  CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES

targetTemplates:
  Framework:
    type: framework
    scheme: {} # To generate default shared schemes: https://github.com/yonaskolb/XcodeGen/issues/215
    sources:
      - ESFramework
      - Supporting Files/Info.plist
    settings:
      PRODUCT_NAME: ESFramework
      APPLICATION_EXTENSION_API_ONLY: YES
  Example:
    type: application
    scheme: {} # To generate default shared schemes: https://github.com/yonaskolb/XcodeGen/issues/215
    sources: ["Examples/${target_name}"]
    settings:
      DEVELOPMENT_TEAM: B86YZY7YJX

targets:
  ESFramework:
    platform: [iOS, tvOS, macOS, watchOS]
    templates: [Framework]

  iOS Example:
    platform: iOS
    templates: [Example]
    settings:
      CODE_SIGN_ENTITLEMENTS: Examples/${target_name}/${target_name}.entitlements
      SUPPORTS_MACCATALYST: YES
    dependencies:
      - target: ESFramework_iOS
      - target: watchOS Example # TODO: Need `platformFilter` https://github.com/yonaskolb/XcodeGen/issues/900

  tvOS Example:
    platform: tvOS
    templates: [Example]
    dependencies:
      - target: ESFramework_tvOS

  macOS Example:
    platform: macOS
    templates: [Example]
    settings:
      CODE_SIGN_ENTITLEMENTS: Examples/${target_name}/${target_name}.entitlements
      CODE_SIGN_IDENTITY: '-'
    dependencies:
      - target: ESFramework_macOS

  watchOS Example:
    platform: watchOS
    type: application.watchapp2
    templates: [Example]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.0x123.iOSExample.watchkitapp
    dependencies:
      - target: watchOS Example Extension

  watchOS Example Extension:
    platform: watchOS
    type: watchkit2-extension
    templates: [Example]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.0x123.iOSExample.watchkitapp.watchkitextension
    dependencies:
      - target: ESFramework_watchOS
