name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate Pod
        run: pod lib lint

      - name: Carthage Build
        run: ./carthage.sh build --no-skip-current
