name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: pod lib lint
      - run: ./carthage.sh build --no-skip-current
