name: Lint Framework

on: [push, pull_request]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate Pod
        run: pod lib lint

      - name: Build with Carthage
        run: carthage build --no-skip-current
