name: Lint Library

on: [push, pull_request]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: pod lib lint
      - run: carthage build --no-skip-current
