name: Lint

on: [push, pull_request]

jobs:
  checkout:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

  lint-pod:
    needs: checkout
    steps:
      - run: pod lib lint

  build-with-carthage:
    needs: checkout
    steps:
      - run: carthage build --no-skip-current
